# Generated by Django 5.0.4 on 2025-08-15 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_sschool_rename_gradeenrollment_pgradeenrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PryPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('year', models.IntegerField()),
                ('term', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.pschool')),
            ],
        ),
        migrations.CreateModel(
            name='SecPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('year', models.IntegerField()),
                ('term', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.sschool')),
            ],
        ),
    ]
