# Generated by Django 5.0.4 on 2025-08-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_prypayments_date_paid_secpayments_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prypayments',
            name='date_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='secpayments',
            name='date_paid',
            field=models.IntegerField(null=True),
        ),
    ]
