# Generated by Django 5.2.1 on 2025-08-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_alter_prypayments_date_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prypayments',
            name='receipt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='secpayments',
            name='receipt',
            field=models.IntegerField(null=True),
        ),
    ]
