# Generated by Django 5.2.1 on 2025-08-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_alter_admin_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
