# Generated by Django 5.2.1 on 2025-08-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_alter_admin_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
    ]
