# Generated by Django 5.2.1 on 2025-08-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pgradeenrollment',
            options={'verbose_name_plural': 'Primary grade enrollments'},
        ),
        migrations.AlterModelOptions(
            name='sgradeenrollment',
            options={'verbose_name_plural': 'Secondary grade enrollments'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterField(
            model_name='pgradeenrollment',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prypayments',
            name='date_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prypayments',
            name='receipt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secpayments',
            name='date_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secpayments',
            name='receipt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sgradeenrollment',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
