# Generated by Django 5.0.4 on 2025-08-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='year',
            field=models.IntegerField(),
        ),
    ]
