# Generated by Django 5.0.4 on 2025-08-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='grand_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
