# Generated by Django 5.0.4 on 2025-08-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='grand_total',
        ),
    ]
