# Generated by Django 5.0.4 on 2025-08-14 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_remove_school_grand_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('registration_status', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='GradeEnrollment',
            new_name='PGradeEnrollment',
        ),
        migrations.RenameModel(
            old_name='School',
            new_name='PSchool',
        ),
        migrations.RenameModel(
            old_name='TeacherData',
            new_name='PTeacherData',
        ),
        migrations.CreateModel(
            name='SGradeEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255)),
                ('male', models.IntegerField(blank=True, null=True)),
                ('female', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.sschool')),
            ],
        ),
        migrations.CreateModel(
            name='STeacherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('male', models.PositiveIntegerField(blank=True, null=True)),
                ('female', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('authorized_establishment', models.PositiveIntegerField(blank=True, null=True)),
                ('vacancies', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.sschool')),
            ],
        ),
    ]
