# Generated by Django 5.0.4 on 2025-08-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_prypayments_secpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='prypayments',
            name='date_paid',
            field=models.IntegerField(default=20250508),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secpayments',
            name='date_paid',
            field=models.IntegerField(default=20250508),
            preserve_default=False,
        ),
    ]
