# Generated by Django 5.2.1 on 2025-08-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_prypayments_receipt_secpayments_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone_number',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
