# Generated by Django 5.0.4 on 2025-08-26 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_alter_admin_options_alter_pgradeenrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('Accounts', 'Accounts'), ('Administration', 'Administration'), ('DSI', 'DSI'), ('Inspectors', 'Inspectors'), ('Remedial', 'Remedial'), ('NonFormal', 'NonFormal'), ('OfficeOrderly', 'OfficeOrderly'), ('HR', 'HR'), ('Aid', 'Aid')], default='IT', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.admin'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='user_images'),
        ),
    ]
